name: CD
on:
  push:
    branches: [ master ]

  workflow_dispatch:

env:
  GF_NAME: main
  SF_NAME: michael-safwat-resume

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: blang/latex:ubuntu
    steps:
      - uses: actions/checkout@v3

      - name: Create personal info
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: personalinfo.tex
          contents: ${{ secrets.personal_info }}

      - name: Generate pdf
        run: pdflatex "${GF_NAME}.tex"

      - name: Rename file
        run: mv ${{ env.GF_NAME }}.pdf ${{ env.SF_NAME }}.pdf

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: ms-resume
          path: ${{ env.SF_NAME }}.pdf
          
      - name: Get current date
        id: date
        run: echo "::set-output name=now::$(date +'%Y-%m-%d')"
        
      - name: Create a release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.date.outputs.now }}
          automatic_release_tag: latest
          prerelease: false
          files: ${{ env.SF_NAME }}.pdf
        
